### ISSUE TITLE
geckodriver message on Raspberry Pi 4

### ISSUE THREAD

**Issue by bondskin** [Herobone/Speedport-Utils#3] opened 2021-01-25 12:54 UTC
Hi,

Not sure if this git is still active.
I installed it on my Raspberry 4, successfully.
But executing speedread.py results in the following error:

Traceback (most recent call last):
  File "./speedread.py", line 194, in <module>
    main()
  File "./speedread.py", line 188, in main
    up, down = readVars(verboose=args.verboose)
  File "./speedread.py", line 42, in readVars
    driver = webdriver.Firefox(options=options, executable_path=geckoPath)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by Herobone** [comment] 2021-01-30 15:12
The issue is according to my knowledge caused by the missing geckodriver package for the Raspberry Pi 4 since it has an ARM architecture and not a x86 architecture.
I did some googleing and apparently Raspberry Pi's use an old version of Firefox too.
It might work on an RaspberryPi if you use an older version of the geckodriver or if you completely switch to Chromium since Raspberrys use an more up to date version of that

**Comment by Herobone** [comment] 2021-06-28 22:14
No answer, will close this issue now! I'm no longer maintaining this project

**Closed by Herobone** 2021-06-28 22:14 UTC
